repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.4
      hooks:
          - id: ruff
            args:
                - --fix
          - id: ruff-format
    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.393
      hooks:
          - id: pyright
