repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.6
      hooks:
          - id: ruff
            args:
                - --fix
          - id: ruff-format
    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.394
      hooks:
          - id: pyright
