[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and import sorting (`I`)
select = ["E", "F", "I"]

# Ignore `E402` (import violations) in all `__init__.py` files
per-file-ignores = { "__init__.py" = ["E402"] }

# Sort imports
isort = { known-first-party = [] } # Add your project's modules here
